src/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

src/main/default/objects/Log__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Log__e/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/LogRecord__c/LogRecord__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/LogRecord__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/LogRecord__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/logging/LogService.cls
public with sharing class LogService {
	public List<LogRecord__c> search(Datetime fromDate, Datetime toDate) {
		if (fromDate == null || toDate == null) {
			return new List<LogRecord__c>();
		}

		return [
				SELECT
						Class__c,
						Context__c,
						Level__c,
						Line__c,
						Message__c,
						Method__c,
						User__c,
						CreatedDate
				FROM LogRecord__c
				WHERE CreatedDate >= :fromDate AND CreatedDate <= :toDate.addDays(1)
				ORDER BY CreatedDate
		];
	}

	public void create(List<Log__e> events) {
		if (!Log.LOG_VIA_EVENTS || events == null) {
			return;
		}
		List<LogRecord__c> records = new List<LogRecord__c>();
		for (Log__e event : events) {
			LogRecord__c record = new LogRecord__c();
			record.Class__c = event.Class__c;
			record.Context__c = event.Context__c;
			record.Level__c = event.Level__c;
			record.Line__c = event.Line__c;
			record.Message__c = event.Message__c;
			record.Method__c = event.Method__c;
			record.User__c = event.User__c;

			records.add(record);
		}

		insert records;
	}
}