src/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

src/main/default/objects/Log__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Log__e/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/SystemSettings__c/SystemSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>System Settings</label>
</CustomObject>

src/main/default/objects/SystemSettings__c/fields/LogFrom__c.field-meta.xml
<CustomField>
    <fullName>LogFrom__c</fullName>
    <label>Log From</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/SystemSettings__c/fields/LogTo__c.field-meta.xml
<CustomField>
    <fullName>LogTo__c</fullName>
    <label>Log To</label>
    <type>Date</type>
</CustomField>

src/main/default/classes/logging/Log_Test.cls
@IsTest
private class Log_Test {
    @IsTest
    private static void debug() {
        enableLogEvents(null);
        String message = '{0}=={1}:{2}';
        List<Object> values = new List<Object>{ 1, '2', false };
        Log.debug(message, values);
        Log__e log = Log.currentEvent;

        System.assertEquals('1==2:false', log.Message__c);
        System.assertEquals(LoggingLevel.DEBUG.name(), log.Level__c);
        System.assertEquals(Request.getCurrent().getRequestId() + '/' + Request.getCurrent().getQuiddity(), log.Context__c);
        System.assertEquals(thisClassName(), log.Class__c);
        System.assertEquals('debug', log.Method__c);
        System.assertEquals(8, log.Line__c);
    }

    @IsTest
    private static void error() {
        enableLogEvents(null);
        Log.error('');

        System.assertEquals(LoggingLevel.ERROR.name(), Log.currentEvent.Level__c);
    }

    @IsTest
    private static void timestampWhenNoContextId() {
        enableLogEvents(null);
        Log.debug('');

        System.assertNotEquals(null, Log.currentEvent.Context__c);
    }

    @IsTest
    private static void noEventsSendWhenDisabled() {
        Log.debug('');

        System.assertEquals(null, Log.currentEvent);
    }

    @IsTest
    private static void noEventsWhenExpired() {
        enableLogEvents(yesterday());
        Log.debug('');

        System.assertEquals(null, Log.currentEvent);
    }

    private static Date yesterday() {
        return System.today().addDays(-1);
    }

    private static String thisClassName() {
        String ns = [SELECT NamespacePrefix FROM Organization].NamespacePrefix + '.';
        return Log_Test.class.getName().removeStart(ns);
    }

    public static void enableLogEvents(Date day) {
        day = day == null ? System.today() : day;
        insert new SystemSettings__c(LogFrom__c = day, LogTo__c = day);
    }
}